"""Test for test coverage by scraping the HTML generated by `coverage`"""
import pathlib

from bs4 import BeautifulSoup

if __name__ == "__main__":
    threshold = 100.0
    html = pathlib.Path("./htmlcov/index.html").read_text()
    soup = BeautifulSoup(html, "html.parser")
    coverage_span = soup.find("span", class_="pc_cov")
    assert coverage_span
    coverage_percentage = coverage_span.get_text()
    coverage = float(coverage_percentage.replace("%", ""))
    assert (
        coverage >= threshold
    ), f"FAILED: {coverage_percentage=} {coverage=} {threshold=}"
    print(f"PASSED: {coverage=} {threshold=}")
