---
site_name: energy-py-linear
site_url: https://energypylinear.adgefficiency.com
repo_url: https://github.com/ADGEfficiency/energy-py-linear
repo_name: energy-py-linear
theme:
  name: material
  logo: static/logo.png
  favicon: static/favicon.ico
  features:
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
plugins:
  - material-plausible
  - search
  - social
  - mike:
      alias_type: symlink
      redirect_template:
      deploy_prefix: ''
      canonical_version:
      version_selector: true
      css_dir: css
      javascript_dir: js
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: [., ..]
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
nav:
  - Getting Started: index.md
  - Assets:
      - Battery: assets/battery.md
      - Combined Heat & Power: assets/chp.md
      - Electric Vehicles: assets/evs.md
      - Heat Pump: assets/heat-pump.md
      - Renewable Generator: assets/renewable-generator.md
  - How To:
      - Optimize Multiple Assets: how-to/dispatch-site.md
      - Optimize for Carbon: how-to/price-carbon.md
      - Optimize for a Forecast: how-to/dispatch-forecast.md
      - Custom Objective Functions: how-to/custom-objectives.md
      - Complex Terms: how-to/complex-terms.md
  - Validation:
      - Battery: validation/battery.md
      # - Combined Heat & Power: validation/chp.md
      - Electric Vehicles: validation/evs.md
      - Heat Pump: validation/heat-pump.md
      - Renewable Generator: validation/renewable-generator.md
  - Changelog: changelog.md
  # - Performance: performance.md
  # - Measure Forecast Quality: index.md

  # - Results: reference/results.md
  # - Asset API: reference/asset-api.md
  # - Site API: reference/site-api.md
  # - Accounting API: index.md

  # - Tutorials:
  #   - Optimizing a Generator with the Asset API: index.md
  #   - Optimizing a Battery & Electric Vehicle Fleet with the Site API: index.md
  #   - Optimizing for Carbon: index.md

  # - Explanation:
  #   - Blocks: index.md
  #   - Spills: index.md
  #   - Valves: index.md
extra:
  version:
    provider: mike
  analytics:
    provider: plausible
    domain: energypylinear.adgefficiency.com
