site_name: energy-py-linear
repo_url: https://github.com/ADGEfficiency/energy-py-linear
repo_name: energy-py-linear
theme:
  name: material
  logo: static/logo.png
  favicon: static/favicon.ico
  features:
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
plugins:
  - search
  - social
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
nav:
  - Getting Started: index.md
  - Optimize Assets: how-to/dispatch-assets.md
  - Optimize a Site: how-to/dispatch-site.md
  - Optimize for Carbon: how-to/price-carbon.md
  - Optimize for a Forecast: how-to/dispatch-forecast.md
  # - Explanation:
  - Validation: validation.md

  # - Measure Forecast Quality: index.md

  # - Results: reference/results.md
  # - Asset API: reference/asset-api.md
  # - Site API: reference/site-api.md
  # - Accounting API: index.md

  # - Tutorials:
  #   - Optimizing a Generator with the Asset API: index.md
  #   - Optimizing a Battery & Electric Vehicle Fleet with the Site API: index.md
  #   - Optimizing for Carbon: index.md

  # - Explanation:
  #   - Blocks: index.md
  #   - Spills: index.md
  #   - Valves: index.md
