name: CI

on:
  pull_request:
    types: [ labeled ]
  push:
    branches: [main]

jobs:
  publish:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
