name: publish

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'publish')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Python Version from `pyproject.toml`
        run: |
          PYTHONVERSION=$(cat pyproject.toml | sed -En "s/^python =//p" | tr -d '" ^')
          echo "PYTHONVERSION=$PYTHONVERSION" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHONVERSION }}

      - name: Publish to PyPi
        run: |
          echo "publish"

      # - name:
      #   run: |
      #     # make publish PYPI_TOKEN=${{ secrets.PYPI_TOKEN }}
      #     echo "no-op"
