name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get python version from poetry pyproject.toml
        run: |
          PYTHONVERSION=$(cat pyproject.toml | sed -En "s/^python =//p" | tr -d '" ^')
          echo "PYTHONVERSION=$PYTHONVERSION" >> $GITHUB_ENV
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHONVERSION }}
      - name: run tests
        run: |
          make test
