---
name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.11.9, 3.12.8]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: make test QUIET=
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.0, 3.12.0]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: make check QUIET=
